pipelines:
  branches:
    develop:
      - step:
          name: "Build"
          deployment: Development
          runs-on:
            - 'self.hosted'
            - 'macos'
          condition:
            changesets:
              includePaths:
                - "ios/**"
                - "android/**"
                - "package.json"
                - "*.env.*"
          script:
            - yarn install
            - fastlane android build type:build env:Development buildNumber:$BITBUCKET_BUILD_NUMBER
            - fastlane ios build type:build env:Development ci:true buildNumber:$BITBUCKET_BUILD_NUMBER
      - step:
          name: "CodePush"
          runs-on:
            - 'self.hosted'
            - 'macos'
          deployment: Test
          script:
            - yarn install
            - yarn codepush:qa
    staging:
      - step:
          name: "Build"
          deployment: Staging
          runs-on:
            - 'self.hosted'
            - 'macos'
          script:
            - yarn install
            - fastlane android build type:build env:Staging buildNumber:$BITBUCKET_BUILD_NUMBER
            - fastlane ios build type:build env:Staging ci:true buildNumber:$BITBUCKET_BUILD_NUMBER
    production:
      - step:
          name: "Build"
          deployment: Production
          runs-on:
            - 'self.hosted'
            - 'macos'
          script:
            - yarn install
            - fastlane android build type:build env:Production buildNumber:$BITBUCKET_BUILD_NUMBER
            - fastlane ios build type:build env:Production ci:true buildNumber:$BITBUCKET_BUILD_NUMBER
